---
resources:
- name: github_issue_resource
  type: git
  icon: github
  source:
    uri: https://github.com/mitodl/concourse-github-issue-resource
    branch: master
    paths:
    - src
    - Cargo.toml
    - Dockerfile

- name: concourse-github-issue-resource
  type: registry-image
  icon: docker
  source:
    tag: latest
    repository: mitodl/concourse-github-issue-resource
    username: ((dockerhub.username))
    password: ((dockerhub.password))

jobs:
- name: build-and-publish-image
  public: true
  plan:
  - get: github_issue_resource
    trigger: true
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: github_issue_resource
      outputs:
      - name: image
      run:
        path: build
      params:
        CONTEXT: github_issue_resource
  - put: concourse-github-issue-resource
    params:
      image: image/image.tar
      additional_tags: github_issue_resource/.git/ref
